name: sayaratech
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  get_storage: ^2.1.1
  google_fonts: ^4.0.5
  hexcolor: ^3.0.1
  font_awesome_flutter: ^10.4.0
  phone_number: ^1.0.0
  email_validator: ^2.1.17
  pin_code_fields: ^7.4.0
  pull_to_refresh: ^2.0.0
  flutter_spinkit: ^5.2.0
  dotted_border: ^2.0.0+3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/

